Add normal card
notaphplover/one-game pull request #1406
Opened 2024-07-03 14:37 UTC by wariofdz

### Changed:

- Added new component `BaseCard.tsx` and his test
- Added new component `TextCard.tsx` and his test
- Added new component `ImageCard.tsx` and his test
- Added new component `NormalCard.tsx` and his test
- Added new function `getCardColorClassName.ts` to select the className `background-color` to the card.

2024-07-04 21:33 UTC, notaphplover requested changes
Nice, we need to apply some suggestions at test level.

2024-07-04 21:33 UTC, notaphplover commented on packages/frontend/web-ui/src/game/components/BaseCard.spec.tsx
> +      expect(existingCardColorClassName).not.toBe('none');
This is not a great assertion since it's allways true

2024-07-04 21:33 UTC, notaphplover commented on packages/frontend/web-ui/src/game/components/ImageCard.spec.tsx
> +      expect(existingCardColorClassName).not.toBe('none');
This is not a great assertion since it's allways true

2024-07-04 21:33 UTC, notaphplover commented on packages/frontend/web-ui/src/game/components/ImageCard.spec.tsx
> +      expect(valueImageCard).toBe('/src/app/images/favicon.ico');
use `imageCardOptionsMock.image` instead of the hardcoded value

2024-07-04 21:33 UTC, notaphplover commented on packages/frontend/web-ui/src/game/components/NormalCard.spec.tsx
> +      expect(existingCardColorClassName).not.toBe('none');
This is not a great assertion since it's allways true

2024-07-04 21:33 UTC, notaphplover commented on packages/frontend/web-ui/src/game/components/NormalCard.spec.tsx
> +      expect(valueCard).toBe('4');
rely on `normalCardOptionsMock` instead of using a hardcoded value.

2024-07-04 21:33 UTC, notaphplover commented on packages/frontend/web-ui/src/game/components/TextCard.spec.tsx
> +      expect(existingCardColorClassName).not.toBe('none');
This is not a great assertion since it's allways true

2024-07-04 21:33 UTC, notaphplover commented on packages/frontend/web-ui/src/game/components/TextCard.spec.tsx
> +      expect(valueCard).toBe('4');
rely on `textCardOptionsMock` instead of using a hardcoded value.

2024-07-04 21:33 UTC, notaphplover commented on packages/frontend/web-ui/src/game/components/BaseCard.spec.tsx
> +  let colorClassMock: string;
This is not a mock, it's a fixture

2024-07-04 21:33 UTC, notaphplover commented on packages/frontend/web-ui/src/game/components/ImageCard.spec.tsx
> +  let imageCardOptionsMock: ImageCardOptions;
This is not a mock, it's a fixture

2024-07-04 21:33 UTC, notaphplover commented on packages/frontend/web-ui/src/game/components/NormalCard.spec.tsx
> +  let normalCardOptionsMock: NormalCardOptions;
This is not a mock, it's a fixture

2024-07-04 21:33 UTC, notaphplover commented on packages/frontend/web-ui/src/game/components/TextCard.spec.tsx
> +  let textCardOptionsMock: TextCardOptions;
This is not a mock, it's a fixture

2024-07-04 21:33 UTC, notaphplover commented on packages/frontend/web-ui/src/game/helpers/getCardColorClassName.spec.ts
> +  let colorMock: apiModels.CardColorV1;
This is not a mock, it's a fixture

2024-07-08 16:19 UTC, wariofdz commented
Added last changes on tests

2024-07-08 16:23 UTC, notaphplover approved these changes

2024-07-08 16:23 UTC, merged