Persist info about token in redux
notaphplover/one-game pull request #759
Opened 2023-11-28 16:04 UTC by wariofdz

### Changed:

1. Added save token in Local Storage.
2. Fixed a bug to Login component.
3. Added new test to check than token is saved in Local Storage.
4. Added new function _createInitialState_ to initialize _authSlice_ from **Redux**.

2023-11-28 20:02 UTC, notaphplover requested changes
Looks great, let's add a test before merging

2023-11-28 20:02 UTC, notaphplover commented on packages/frontend/web-ui/src/app/store/helpers/createInitialState.js
> +export const createInitialState = () => {
This module should be tested

2023-11-29 15:09 UTC, wariofdz commented on packages/frontend/web-ui/src/app/store/helpers/createInitialState.js
> +export const createInitialState = () => {
Done!

2023-11-29 16:40 UTC, notaphplover approved these changes

2023-11-29 16:40 UTC, merged